"""Regression tests for the post-export IQVIA verifier (app.enrichment.iqvia_verify).

These tests run fully offline against committed synthetic fixtures — real IQVIA
sample data is not checked into the repo (see tests/test_iqvia.py).  The fixtures
are generated by ``build_fixtures()`` below; running this module as a script
regenerates them:

    python -m tests.test_iqvia_verify --regenerate

Two committed fixtures under tests/fixtures/iqvia/:
  * verify_raw.xlsx       — a raw IQVIA-format file (one 'data' sheet)
  * verify_workbook.xlsx  — a finished export workbook, produced by the REAL
                            matcher + the real vertical-sheet writer.

The workbook bakes in:
  * Three golden DINs at their human-verified MAT 12/2025 values:
        02516187  SANIS / PROGESTERONE        Units 218,591  Dollars 21,215,081
        02493578  AURO  / AURO-PROGESTERONE   Units 233,159  Dollars 13,005,865
        00585092  PFIZER/ DEPO-PROVERA        Units 262,834  Dollars  8,853,659
  * One planted CONFIDENT-WRONG match: a DIN for "NOVA-LUTEIN" (same maker,
    same strength as the IQVIA group "NOVA-PROGEST") receives NOVA-PROGEST's
    numbers because company similarity alone drags the matcher past its gate.
    Its source rows re-sum perfectly, so a sum-only checker would miss it.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import pytest

from app.enrichment.iqvia import match_iqvia_to_sheet1
from app.enrichment.iqvia_verify import verify

_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "iqvia"
_RAW_PATH = _FIXTURE_DIR / "verify_raw.xlsx"
_WORKBOOK_PATH = _FIXTURE_DIR / "verify_workbook.xlsx"

# IQVIA metric columns for the synthetic file (mirror the real "MAT MM/YYYY" form).
_UNITS = "Units MAT 12/2025"
_DOLLARS = "Dollars MAT 12/2025"

# Golden anchors (din -> (units, dollars)) — from tests/test_iqvia.py.
_GOLDEN = {
    "02516187": (218591, 21215081),
    "02493578": (233159, 13005865),
    "00585092": (262834, 8853659),
}

# The planted confident-wrong case.
_BAD_DIN = "02999001"
_NOVA_PROGEST = (444555, 99887766)   # IQVIA "NOVA-PROGEST" group values


def _raw_iqvia_df() -> pd.DataFrame:
    """Raw IQVIA rows (already one-per-group; collapse is a no-op sum on these)."""
    return pd.DataFrame([
        # Three golden groups whose Product/Manufacturer/Strength match real DINs.
        {"Combined Molecule": "PROGESTERONE", "Product": "PROGESTERONE",
         "Manufacturer": "SANIS HEALTH INC", "Strength": "100MG",
         _UNITS: _GOLDEN["02516187"][0], _DOLLARS: _GOLDEN["02516187"][1]},
        {"Combined Molecule": "PROGESTERONE", "Product": "AURO-PROGESTERONE",
         "Manufacturer": "AURO PHARMA INC", "Strength": "100MG",
         _UNITS: _GOLDEN["02493578"][0], _DOLLARS: _GOLDEN["02493578"][1]},
        {"Combined Molecule": "MEDROXYPROGESTERONE ACETATE", "Product": "DEPO-PROVERA",
         "Manufacturer": "PFIZER CANADA ULC", "Strength": "150MG/ML",
         _UNITS: _GOLDEN["00585092"][0], _DOLLARS: _GOLDEN["00585092"][1]},
        # The real seller of NOVA-PROGEST has NO DIN in Sheet 1; only its sibling
        # NOVA-LUTEIN (same maker, same strength) does — the confident-wrong trap.
        {"Combined Molecule": "PROGESTERONE", "Product": "NOVA-PROGEST",
         "Manufacturer": "NOVADUS PHARMA INC", "Strength": "200MG",
         _UNITS: _NOVA_PROGEST[0], _DOLLARS: _NOVA_PROGEST[1]},
    ])


def _sheet1_df() -> pd.DataFrame:
    """Internal-keyed Sheet 1 (what the export matches IQVIA against)."""
    return pd.DataFrame([
        {"din": "02516187", "ingredient": "PROGESTERONE", "brand_name": "PROGESTERONE",
         "company": "SANIS HEALTH INC", "strength": "100 MG", "status": "Marketed"},
        {"din": "02493578", "ingredient": "PROGESTERONE", "brand_name": "AURO-PROGESTERONE",
         "company": "AURO PHARMA INC", "strength": "100 MG", "status": "Marketed"},
        {"din": "00585092", "ingredient": "MEDROXYPROGESTERONE ACETATE",
         "brand_name": "DEPO-PROVERA", "company": "PFIZER CANADA ULC",
         "strength": "150 MG", "status": "Marketed"},
        # The sibling DIN that the matcher confidently-wrongly lands NOVA-PROGEST on.
        {"din": _BAD_DIN, "ingredient": "PROGESTERONE", "brand_name": "NOVA-LUTEIN",
         "company": "NOVADUS PHARMA INC", "strength": "200 MG", "status": "Marketed"},
    ])


def build_fixtures() -> None:
    """Generate the committed fixtures using the REAL matcher + sheet writer."""
    import openpyxl
    from app.enrichment.workbook import _write_vertical_sheet, _SHEET1_COLS

    _FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    collapsed = _raw_iqvia_df()
    enriched, _ = match_iqvia_to_sheet1(_sheet1_df(), collapsed)

    # Reorder to the canonical Sheet-1 column order (metric cols trail), exactly
    # as build_workbook_multiproduct does, then write via the real vertical writer.
    present = set(enriched.columns)
    ordered = [c for c in _SHEET1_COLS if c in present]
    ordered += [c for c in enriched.columns if c not in set(_SHEET1_COLS)]
    enriched = enriched[ordered]

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "DPD + NOC + Patents"
    _write_vertical_sheet(ws, enriched, [("progesterone", "EDD6EB")])
    wb.save(_WORKBOOK_PATH)

    # Raw IQVIA file: a single 'data' sheet, header row 1, data from row 2.
    with pd.ExcelWriter(_RAW_PATH, engine="openpyxl") as xw:
        _raw_iqvia_df().to_excel(xw, sheet_name="data", index=False)


def _fixtures_present() -> bool:
    return _RAW_PATH.is_file() and _WORKBOOK_PATH.is_file()


pytestmark = pytest.mark.skipif(
    not _fixtures_present(),
    reason=f"verifier fixtures missing — run: python -m tests.test_iqvia_verify --regenerate",
)


@pytest.fixture(scope="module")
def report():
    return verify(str(_WORKBOOK_PATH), str(_RAW_PATH))


# ── Golden anchors: the three known-good DINs verify clean to exact values ─────

class TestGoldenAnchors:
    @pytest.mark.parametrize("din", list(_GOLDEN))
    def test_golden_exact_values(self, report, din):
        r = report.get(din)
        assert r is not None, f"DIN {din} not found among enriched DINs"
        units, dollars = _GOLDEN[din]
        assert r.values.get(_UNITS) == units
        assert r.values.get(_DOLLARS) == dollars

    @pytest.mark.parametrize("din", list(_GOLDEN))
    def test_golden_not_suspicious(self, report, din):
        r = report.get(din)
        assert r.suspicion == 0, f"golden DIN {din} wrongly flagged: {r.flags} {r.evidence}"
        assert not r.flags


# ── The point: the verifier catches a confident-wrong match ───────────────────

class TestCatchesBadMatch:
    def test_bad_din_carries_wrong_groups_numbers(self, report):
        """Sanity: the workbook really does carry NOVA-PROGEST's numbers on the
        NOVA-LUTEIN DIN — i.e. the trap is actually set (a sum-only check passes)."""
        r = report.get(_BAD_DIN)
        assert r is not None
        assert r.values.get(_UNITS) == _NOVA_PROGEST[0]
        assert r.values.get(_DOLLARS) == _NOVA_PROGEST[1]

    def test_bad_din_is_flagged(self, report):
        r = report.get(_BAD_DIN)
        assert r.suspicion > 0, "verifier failed to flag the confident-wrong match"
        assert "company_carried" in r.flags, (
            f"expected the company-carried fingerprint; got {r.flags}"
        )

    def test_bad_din_ranks_top(self, report):
        assert report.suspicious, "no suspicious matches reported"
        assert report.suspicious[0].din == _BAD_DIN

    def test_only_the_bad_din_is_suspicious(self, report):
        assert {d.din for d in report.suspicious} == {_BAD_DIN}

    def test_report_not_ok(self, report):
        assert report.ok is False


# ── Verifier tuning: matcher fix + recall + precision-downrank regressions ────
# These exercise the verifier changes that accompanied the matcher's exact-brand
# priority fix, using small temp workbooks (the real IQVIA file is not committed).

import io

from app.enrichment.iqvia import (
    collapse_iqvia,
    parse_iqvia,
    _is_generic_brand,
    _GENERIC_FILLER_WORDS,
)
from app.enrichment.iqvia_verify import _is_truncated_brand, _is_subsequence


def _write_raw_iqvia(path: Path, rows: list[dict]) -> None:
    cols = ["Combined Molecule", "Product", "Manufacturer", "Strength", _UNITS, _DOLLARS]
    df = pd.DataFrame(rows)
    for c in cols:
        if c not in df.columns:
            df[c] = ""
    with pd.ExcelWriter(path, engine="openpyxl") as xw:
        df[cols].to_excel(xw, sheet_name="data", index=False)


def _write_workbook(path: Path, enriched: pd.DataFrame) -> None:
    keys = ["din", "ingredient", "brand_name", "company", "strength", "status"]
    metric = [c for c in enriched.columns if c not in keys]
    ordered = [k for k in keys if k in enriched.columns] + metric
    with pd.ExcelWriter(path, engine="openpyxl") as xw:
        enriched[ordered].to_excel(xw, sheet_name="DPD + NOC + Patents", index=False)


def _match_and_verify(tmp_path, sheet1: pd.DataFrame, raw_rows: list[dict]):
    """Match sheet1 against raw IQVIA, write both files, run the real verifier."""
    raw = tmp_path / "raw.xlsx"
    wb = tmp_path / "wb.xlsx"
    _write_raw_iqvia(raw, raw_rows)
    collapsed = collapse_iqvia(parse_iqvia(raw.read_bytes()))
    enriched, _ = match_iqvia_to_sheet1(sheet1, collapsed)
    _write_workbook(wb, enriched)
    return verify(str(wb), str(raw))


class TestTruncationVsSibling:
    """The downrank tier must separate a benign truncated label from a wrong
    sibling — the distinction that keeps the verifier's core catch alive."""

    def test_truncated_combo_is_abbreviation(self):
        assert _is_truncated_brand(
            "mylan-efavirnz/emtr/teno",
            "mylan-efavirenz/emtricitabine/tenofovir disoproxil fumarate",
        )

    def test_sibling_swap_is_not_abbreviation(self):
        # nova-progest vs nova-lutein share only the "nova" stem — different drugs.
        assert not _is_truncated_brand("nova-progest", "nova-lutein")

    def test_subsequence_basic(self):
        assert _is_subsequence("abc", "axbxc")
        assert not _is_subsequence("acb", "axbxc")

    def test_generic_usp_label_is_generic(self):
        assert _is_generic_brand(
            "amlodipine besylate usp", "AMLODIPINE", _GENERIC_FILLER_WORDS
        )

    def test_branded_label_is_not_generic(self):
        assert not _is_generic_brand("pms-amlodipine", "AMLODIPINE", _GENERIC_FILLER_WORDS)


class TestVerifierDownrankTier:
    """Benign company-carried matches (correct, but weak brand leg) move to the
    low-priority tier; genuine sibling swaps stay high."""

    def test_generic_usp_label_downranked(self, tmp_path):
        sheet1 = pd.DataFrame([
            {"din": "02419564", "ingredient": "AMLODIPINE (AMLODIPINE BESYLATE)",
             "brand_name": "ACH-AMLODIPINE", "company": "ACCORD HEALTHCARE INC",
             "strength": "5 MG", "status": "Marketed"},
        ])
        rep = _match_and_verify(tmp_path, sheet1, [
            {"Combined Molecule": "AMLODIPINE", "Product": "AMLODIPINE BESYLATE USP",
             "Manufacturer": "ACCORD HEALTHCARE", "Strength": "5MG",
             _UNITS: 11231, _DOLLARS: 112310},
        ])
        r = rep.get("02419564")
        assert r is not None and r.values.get(_UNITS) == 11231  # match is correct
        assert r.tier == "low"
        assert r not in rep.suspicious and r in rep.low_priority

    def test_truncated_combo_downranked(self, tmp_path):
        sheet1 = pd.DataFrame([
            {"din": "02461412",
             "ingredient": "EFAVIRENZ; EMTRICITABINE; TENOFOVIR DISOPROXIL FUMARATE",
             "brand_name": "MYLAN-EFAVIRENZ/EMTRICITABINE/TENOFOVIR DISOPROXIL FUMARATE",
             "company": "MYLAN PHARMACEUTICALS ULC",
             "strength": "600 MG; 200 MG; 300 MG", "status": "Marketed"},
        ])
        rep = _match_and_verify(tmp_path, sheet1, [
            {"Combined Molecule": "EFAVIRENZ:EMTRICITABINE:TENOFOVIR DISOPROXIL FUMARATE",
             "Product": "MYLAN-EFAVIRNZ/EMTR/TENO", "Manufacturer": "MYLAN PHARMA",
             "Strength": "0.6GM/300MG/200MG", _UNITS: 500, _DOLLARS: 5000},
        ])
        r = rep.get("02461412")
        assert r is not None and r.tier == "low"
        assert r in rep.low_priority

    def test_sibling_swap_stays_high(self, tmp_path):
        """A same-company sibling (NOVA-LUTEIN carrying NOVA-PROGEST's numbers) is a
        genuine confident-wrong match — it must NOT be downranked."""
        sheet1 = pd.DataFrame([
            {"din": "02999001", "ingredient": "PROGESTERONE",
             "brand_name": "NOVA-LUTEIN", "company": "NOVADUS PHARMA INC",
             "strength": "200 MG", "status": "Marketed"},
        ])
        rep = _match_and_verify(tmp_path, sheet1, [
            {"Combined Molecule": "PROGESTERONE", "Product": "NOVA-PROGEST",
             "Manufacturer": "NOVADUS PHARMA INC", "Strength": "200MG",
             _UNITS: 444555, _DOLLARS: 99887766},
        ])
        r = rep.get("02999001")
        assert r is not None
        assert "company_carried" in r.flags
        assert r.tier == "high" and r in rep.suspicious


class TestVerifierExactCounterpartRecall:
    """A cross-company swap whose exact-brand counterpart sits just under
    RIVAL_MARGIN must still be flagged (the 02522519-class miss)."""

    def test_exact_counterpart_flagged_below_margin(self, tmp_path):
        # Hand-stamp the WRONG DIN (the matcher itself now avoids this), so the
        # verifier must independently catch it. PRZ DIN carries the PMS group; the
        # exact PMS DIN scores 100 vs assigned 85.7 — margin 14.3 < 15.
        sheet1 = pd.DataFrame([
            {"din": "02284065", "ingredient": "AMLODIPINE (AMLODIPINE BESYLATE)",
             "brand_name": "PMS-AMLODIPINE", "company": "PHARMASCIENCE INC",
             "strength": "5 MG", "status": "Marketed", _UNITS: None, _DOLLARS: None},
            {"din": "02522519", "ingredient": "AMLODIPINE (AMLODIPINE BESYLATE)",
             "brand_name": "PRZ-AMLODIPINE", "company": "PHARMARIS CANADA INC",
             "strength": "5 MG", "status": "Marketed", _UNITS: 33489, _DOLLARS: 334890},
        ])
        raw = tmp_path / "raw.xlsx"
        wb = tmp_path / "wb.xlsx"
        _write_raw_iqvia(raw, [
            {"Combined Molecule": "AMLODIPINE", "Product": "PMS-AMLODIPINE",
             "Manufacturer": "PHARMASCIENCE", "Strength": "5MG",
             _UNITS: 33489, _DOLLARS: 334890},
        ])
        _write_workbook(wb, sheet1)
        rep = verify(str(wb), str(raw))
        r = rep.get("02522519")
        assert r is not None
        assert "better_din_for_group" in r.flags
        assert any("exact-brand counterpart" in e for e in r.evidence)


class TestVerifierAggregationAndDuplicates:
    def test_aggregated_value_not_orphaned(self, tmp_path):
        """An aggregated DIN value (sum of generic + exact group) must be recognised
        as a same-company aggregate, never flagged value_orphan."""
        sheet1 = pd.DataFrame([
            {"din": "02314908", "ingredient": "METFORMIN HYDROCHLORIDE",
             "brand_name": "PRO-METFORMIN", "company": "PRO DOC LIMITEE",
             "strength": "500 MG", "status": "Marketed"},
            {"din": "02246834", "ingredient": "METFORMIN HYDROCHLORIDE",
             "brand_name": "SANDOZ METFORMIN", "company": "SANDOZ CANADA INC",
             "strength": "500 MG", "status": "Marketed"},
        ])
        rep = _match_and_verify(tmp_path, sheet1, [
            {"Combined Molecule": "METFORMIN", "Product": "METFORMIN",
             "Manufacturer": "PRO DOC", "Strength": "500MG", _UNITS: 37942, _DOLLARS: 379420},
            {"Combined Molecule": "METFORMIN", "Product": "PRO-METFORMIN",
             "Manufacturer": "PRO DOC", "Strength": "0.5GM", _UNITS: 48, _DOLLARS: 480},
        ])
        r = rep.get("02314908")
        assert r is not None
        assert r.values.get(_UNITS) == 37942 + 48
        assert "value_orphan" not in r.flags
        assert any("aggregate" in e for e in r.evidence)

    def test_duplicate_din_no_false_rerun_divergence(self, tmp_path):
        """A combination DIN that appears in two ingredient blocks (same DIN, the
        second row blank) must not trip rerun_divergence from the blank row
        overwriting the real value in the canonical map."""
        # Same DIN in two ingredient blocks: the FULL combination ingredient is
        # repeated in both rows (the block differs by which ingredient was queried,
        # not by truncating the ingredient string).
        row = {"din": "02330482", "ingredient": "VALSARTAN; HYDROCHLOROTHIAZIDE",
               "brand_name": "VALSARTAN HCT", "company": "SANIS HEALTH INC",
               "strength": "80 MG; 12.5 MG", "status": "Marketed"}
        sheet1 = pd.DataFrame([dict(row), dict(row)])
        rep = _match_and_verify(tmp_path, sheet1, [
            {"Combined Molecule": "HYDROCHLOROTHIAZIDE:VALSARTAN", "Product": "VALSARTAN HCT",
             "Manufacturer": "SANIS HEALTH INC", "Strength": "80MG/12.5MG",
             _UNITS: 5000, _DOLLARS: 50000},
        ])
        r = rep.get("02330482")
        assert r is not None
        assert "rerun_divergence" not in r.flags
        assert r.suspicion == 0


# ── Allow `python -m tests.test_iqvia_verify --regenerate` ────────────────────

if __name__ == "__main__":
    if "--regenerate" in sys.argv:
        build_fixtures()
        print(f"Wrote {_RAW_PATH}")
        print(f"Wrote {_WORKBOOK_PATH}")
    else:
        print("Pass --regenerate to (re)build the committed fixtures.")
